export const surahNames = [
    { id: 1, english: "Al-Fatihah", arabic: "الفاتحة" },
    { id: 2, english: "Al-Baqarah", arabic: "البقرة" },
    { id: 3, english: "Ali Imran", arabic: "آل عمران" },
    { id: 4, english: "An-Nisa'", arabic: "النساء" },
    { id: 5, english: "Al-Ma'idah", arabic: "المائدة" },
    { id: 6, english: "Al-An'am", arabic: "الأنعام" },
    { id: 7, english: "Al-A'raf", arabic: "الأعراف" },
    { id: 8, english: "Al-Anfal", arabic: "الأنفال" },
    { id: 9, english: "At-Tawbah", arabic: "التوبة" },
    { id: 10, english: "Yunus", arabic: "يونس" },
    { id: 11, english: "Hud", arabic: "هود" },
    { id: 12, english: "Yusuf", arabic: "يوسف" },
    { id: 13, english: "Ar-Ra'd", arabic: "الرعد" },
    { id: 14, english: "Ibrahim", arabic: "إبراهيم" },
    { id: 15, english: "Al-Hijr", arabic: "الحجر" },
    { id: 16, english: "An-Nahl", arabic: "النحل" },
    { id: 17, english: "Al-Isra'", arabic: "الإسراء" },
    { id: 18, english: "Al-Kahf", arabic: "الكهف" },
    { id: 19, english: "Maryam", arabic: "مريم" },
    { id: 20, english: "Ta-Ha", arabic: "طه" },
    { id: 21, english: "Al-Anbiya'", arabic: "الأنبياء" },
    { id: 22, english: "Al-Hajj", arabic: "الحج" },
    { id: 23, english: "Al-Mu'minun", arabic: "المؤمنون" },
    { id: 24, english: "An-Nur", arabic: "النور" },
    { id: 25, english: "Al-Furqan", arabic: "الفرقان" },
    { id: 26, english: "Ash-Shu'ara", arabic: "الشعراء" },
    { id: 27, english: "An-Naml", arabic: "النمل" },
    { id: 28, english: "Al-Qasas", arabic: "القصص" },
    { id: 29, english: "Al-Ankabut", arabic: "العنكبوت" },
    { id: 30, english: "Ar-Rum", arabic: "الروم" },
    { id: 31, english: "Luqman", arabic: "لقمان" },
    { id: 32, english: "As-Sajda", arabic: "السجدة" },
    { id: 33, english: "Al-Ahzab", arabic: "الأحزاب" },
    { id: 34, english: "Saba'", arabic: "سبأ" },
    { id: 35, english: "Fatir", arabic: "فاطر" },
    { id: 36, english: "Ya-Sin", arabic: "يس" },
    { id: 37, english: "As-Saffat", arabic: "الصافات" },
    { id: 38, english: "Sad", arabic: "ص" },
    { id: 39, english: "Az-Zumar", arabic: "الزمر" },
    { id: 40, english: "Ghafir", arabic: "غافر" },
    { id: 41, english: "Fussilat", arabic: "فصلت" },
    { id: 42, english: "Ash-Shura", arabic: "الشورى" },
    { id: 43, english: "Az-Zukhruf", arabic: "الزخرف" },
    { id: 44, english: "Ad-Dukhan", arabic: "الدخان" },
    { id: 45, english: "Al-Jathiyah", arabic: "الجاثية" },
    { id: 46, english: "Al-Ahqaf", arabic: "الأحقاف" },
    { id: 47, english: "Muhammad", arabic: "محمد" },
    { id: 48, english: "Al-Fath", arabic: "الفتح" },
    { id: 49, english: "Al-Hujurat", arabic: "الحجرات" },
    { id: 50, english: "Qaf", arabic: "ق" },
    { id: 51, english: "Adh-Dhariyat", arabic: "الذاريات" },
    { id: 52, english: "At-Tur", arabic: "الطور" },
    { id: 53, english: "An-Najm", arabic: "النجم" },
    { id: 54, english: "Al-Qamar", arabic: "القمر" },
    { id: 55, english: "Ar-Rahman", arabic: "الرحمن" },
    { id: 56, english: "Al-Waqi'ah", arabic: "الواقعة" },
    { id: 57, english: "Al-Hadid", arabic: "الحديد" },
    { id: 58, english: "Al-Mujadila", arabic: "المجادلة" },
    { id: 59, english: "Al-Hashr", arabic: "الحشر" },
    { id: 60, english: "Al-Mumtahanah", arabic: "الممتحنة" },
    { id: 61, english: "As-Saff", arabic: "الصف" },
    { id: 62, english: "Al-Jumu'ah", arabic: "الجمعة" },
    { id: 63, english: "Al-Munafiqun", arabic: "المنافقون" },
    { id: 64, english: "At-Taghabun", arabic: "التغابن" },
    { id: 65, english: "At-Talaq", arabic: "الطلاق" },
    { id: 66, english: "At-Tahrim", arabic: "التحريم" },
    { id: 67, english: "Al-Mulk", arabic: "الملك" },
    { id: 68, english: "Al-Qalam", arabic: "القلم" },
    { id: 69, english: "Al-Haqqah", arabic: "الحاقة" },
    { id: 70, english: "Al-Ma'arij", arabic: "المعارج" },
    { id: 71, english: "Nuh", arabic: "نوح" },
    { id: 72, english: "Al-Jinn", arabic: "الجن" },
    { id: 73, english: "Al-Muzzammil", arabic: "المزمل" },
    { id: 74, english: "Al-Muddathir", arabic: "المدثر" },
    { id: 75, english: "Al-Qiyamah", arabic: "القيامة" },
    { id: 76, english: "Al-Insan", arabic: "الإنسان" },
    { id: 77, english: "Al-Mursalat", arabic: "المرسلات" },
    { id: 78, english: "An-Naba'", arabic: "النبأ" },
    { id: 79, english: "An-Nazi'at", arabic: "النازعات" },
    { id: 80, english: "'Abasa", arabic: "عبس" },
    { id: 81, english: "At-Takwir", arabic: "التكوير" },
    { id: 82, english: "Al-Infitar", arabic: "الإنفطار" },
    { id: 83, english: "Al-Mutaffifin", arabic: "المطففين" },
    { id: 84, english: "Al-Inshiqaq", arabic: "الإنشقاق" },
    { id: 85, english: "Al-Buruj", arabic: "البروج" },
    { id: 86, english: "At-Tariq", arabic: "الطارق" },
    { id: 87, english: "Al-A'la", arabic: "الأعلى" },
    { id: 88, english: "Al-Ghashiyah", arabic: "الغاشية" },
    { id: 89, english: "Al-Fajr", arabic: "الفجر" },
    { id: 90, english: "Al-Balad", arabic: "البلد" },
    { id: 91, english: "Ash-Shams", arabic: "الشمس" },
    { id: 92, english: "Al-Layl", arabic: "الليل" },
    { id: 93, english: "Ad-Duha", arabic: "الضحى" },
    { id: 94, english: "Ash-Sharh", arabic: "الشرح" },
    { id: 95, english: "At-Tin", arabic: "التين" },
    { id: 96, english: "Al-'Alaq", arabic: "العلق" },
    { id: 97, english: "Al-Qadr", arabic: "القدر" },
    { id: 98, english: "Al-Bayyinah", arabic: "البينة" },
    { id: 99, english: "Az-Zalzalah", arabic: "الزلزلة" },
    { id: 100, english: "Al-'Adiyat", arabic: "العاديات" },
    { id: 101, english: "Al-Qari'ah", arabic: "القارعة" },
    { id: 102, english: "At-Takathur", arabic: "التكاثر" },
    { id: 103, english: "Al-'Asr", arabic: "العصر" },
    { id: 104, english: "Al-Humazah", arabic: "الهمزة" },
    { id: 105, english: "Al-Fil", arabic: "الفيل" },
    { id: 106, english: "Quraish", arabic: "قريش" },
    { id: 107, english: "Al-Ma'un", arabic: "الماعون" },
    { id: 108, english: "Al-Kawthar", arabic: "الكوثر" },
    { id: 109, english: "Al-Kafirun", arabic: "الكافرون" },
    { id: 110, english: "An-Nasr", arabic: "النصر" },
    { id: 111, english: "Al-Masad", arabic: "المسد" },
    { id: 112, english: "Al-Ikhlas", arabic: "الإخلاص" },
    { id: 113, english: "Al-Falaq", arabic: "الفلق" },
    { id: 114, english: "An-Nas", arabic: "الناس" }
  ];
  
  export const surahDetails = [
    {
      id: 1,
      name: "Al-Fatihah",
      verses: "The Opening - Verses",
      chapters: "1-7",
    },
    {
      id: 2,
      name: "Al-Baqarah",
      verses: "The Cow - 286 Verses",
      chapters: "1-286",
    },
    {
      id: 3,
      name: "Ali Imran",
      verses: "Family of Imran - 200 Verses",
      chapters: "1-200",
    },
    {
      id: 4,
      name: "An-Nisa'",
      verses: "The Women - 176 Verses",
      chapters: "1-176",
    },
    {
      id: 5,
      name: "Al-Ma'idah",
      verses: "The Table Spread - 120 Verses",
      chapters: "1-120",
    },
    {
      id: 6,
      name: "Al-An'am",
      verses: "The Cattle - 165 Verses",
      chapters: "1-165",
    },
    {
      id: 7,
      name: "Al-A'raf",
      verses: "The Heights - 206 Verses",
      chapters: "1-206",
    },
    {
      id: 8,
      name: "Al-Anfal",
      verses: "The Spoils of War - 75 Verses",
      chapters: "1-75",
    },
    {
      id: 9,
      name: "At-Tawbah",
      verses: "The Repentance - 129 Verses",
      chapters: "1-129",
    },
    {
      id: 10,
      name: "Yunus",
      verses: "Jonah - 109 Verses",
      chapters: "1-109",
    },
    {
      id: 11,
      name: "Hud",
      verses: "Hud - 123 Verses",
      chapters: "1-123",
    },
    {
      id: 12,
      name: "Yusuf",
      verses: "Joseph - 111 Verses",
      chapters: "1-111",
    },
    {
      id: 13,
      name: "Ar-Ra'd",
      verses: "The Thunder - 43 Verses",
      chapters: "1-43",
    },
    {
      id: 14,
      name: "Ibrahim",
      verses: "Abraham - 52 Verses",
      chapters: "1-52",
    },
    {
      id: 15,
      name: "Al-Hijr",
      verses: "The Rocky Tract - 99 Verses",
      chapters: "1-99",
    },
    {
      id: 16,
      name: "An-Nahl",
      verses: "The Bee - 128 Verses",
      chapters: "1-128",
    },
    {
      id: 17,
      name: "Al-Isra'",
      verses: "The Night Journey - 111 Verses",
      chapters: "1-111",
    },
    {
      id: 18,
      name: "Al-Kahf",
      verses: "The Cave - 110 Verses",
      chapters: "1-110",
    },
    {
      id: 19,
      name: "Maryam",
      verses: "Mary - 98 Verses",
      chapters: "1-98",
    },
    {
      id: 20,
      name: "Ta-Ha",
      verses: "Ta-Ha - 135 Verses",
      chapters: "1-135",
    },
    {
      id: 21,
      name: "Al-Anbiya'",
      verses: "The Prophets - 112 Verses",
      chapters: "1-112",
    },
    {
      id: 22,
      name: "Al-Hajj",
      verses: "The Pilgrimage - 78 Verses",
      chapters: "1-78",
    },
    {
      id: 23,
      name: "Al-Mu'minun",
      verses: "The Believers - 118 Verses",
      chapters: "1-118",
    },
    {
      id: 24,
      name: "An-Nur",
      verses: "The Light - 64 Verses",
      chapters: "1-64",
    },
    {
      id: 25,
      name: "Al-Furqan",
      verses: "The Criterion - 77 Verses",
      chapters: "1-77",
    },
    {
      id: 26,
      name: "Ash-Shu'ara",
      verses: "The Poets - 227 Verses",
      chapters: "1-227",
    },
    {
      id: 27,
      name: "An-Naml",
      verses: "The Ant - 93 Verses",
      chapters: "1-93",
    },
    {
      id: 28,
      name: "Al-Qasas",
      verses: "The Stories - 88 Verses",
      chapters: "1-88",
    },
    {
      id: 29,
      name: "Al-Ankabut",
      verses: "The Spider - 69 Verses",
      chapters: "1-69",
    },
    {
      id: 30,
      name: "Ar-Rum",
      verses: "The Romans - 60 Verses",
      chapters: "1-60",
    },
    {
      id: 31,
      name: "Luqman",
      verses: "Luqman - 34 Verses",
      chapters: "1-34",
    },
    {
      id: 32,
      name: "As-Sajda",
      verses: "The Prostration - 30 Verses",
      chapters: "1-30",
    },
    {
      id: 33,
      name: "Al-Ahzab",
      verses: "The Combined Forces - 73 Verses",
      chapters: "1-73",
    },
    {
      id: 34,
      name: "Saba'",
      verses: "Sheba - 54 Verses",
      chapters: "1-54",
    },
    {
      id: 35,
      name: "Fatir",
      verses: "The Originator - 45 Verses",
      chapters: "1-45",
    },
    {
      id: 36,
      name: "Ya-Sin",
      verses: "Ya Sin - 83 Verses",
      chapters: "1-83",
    },
    {
      id: 37,
      name: "As-Saffat",
      verses: "Those Ranged in Ranks - 182 Verses",
      chapters: "1-182",
    },
    {
      id: 38,
      name: "Sad",
      verses: "The Letter 'Saad' - 88 Verses",
      chapters: "1-88",
    },
    {
      id: 39,
      name: "Az-Zumar",
      verses: "The Groups - 75 Verses",
      chapters: "1-75",
    },
    {
      id: 40,
      name: "Ghafir",
      verses: "The Forgiver - 85 Verses",
      chapters: "1-85",
    },
    {
      id: 41,
      name: "Fussilat",
      verses: "Explained in Detail - 54 Verses",
      chapters: "1-54",
    },
    {
      id: 42,
      name: "Ash-Shura",
      verses: "The Consultation - 53 Verses",
      chapters: "1-53",
    },
    {
      id: 43,
      name: "Az-Zukhruf",
      verses: "The Gold Adornments - 89 Verses",
      chapters: "1-89",
    },
    {
      id: 44,
      name: "Ad-Dukhan",
      verses: "The Smoke - 59 Verses",
      chapters: "1-59",
    },
    {
      id: 45,
      name: "Al-Jathiyah",
      verses: "The Crouching - 37 Verses",
      chapters: "1-37",
    },
    {
      id: 46,
      name: "Al-Ahqaf",
      verses: "The Wind-Curved Sandhills - 35 Verses",
      chapters: "1-35",
    },
    {
      id: 47,
      name: "Muhammad",
      verses: "Muhammad - 38 Verses",
      chapters: "1-38",
    },
    {
      id: 48,
      name: "Al-Fath",
      verses: "The Victory - 29 Verses",
      chapters: "1-29",
    },
    {
      id: 49,
      name: "Al-Hujurat",
      verses: "The Rooms - 18 Verses",
      chapters: "1-18",
    },
    {
      id: 50,
      name: "Qaf",
      verses: "The Letter 'Qaf' - 45 Verses",
      chapters: "1-45",
    },
    {
      id: 51,
      name: "Adh-Dhariyat",
      verses: "The Winnowing Winds - 60 Verses",
      chapters: "1-60",
    },
    {
      id: 52,
      name: "At-Tur",
      verses: "The Mount - 49 Verses",
      chapters: "1-49",
    },
    {
      id: 53,
      name: "An-Najm",
      verses: "The Star - 62 Verses",
      chapters: "1-62",
    },
    {
      id: 54,
      name: "Al-Qamar",
      verses: "The Moon - 55 Verses",
      chapters: "1-55",
    },
    {
      id: 55,
      name: "Ar-Rahman",
      verses: "The Beneficent - 78 Verses",
      chapters: "1-78",
    },
    {
      id: 56,
      name: "Al-Waqi'ah",
      verses: "The Inevitable - 96 Verses",
      chapters: "1-96",
    },
    {
      id: 57,
      name: "Al-Hadid",
      verses: "The Iron - 29 Verses",
      chapters: "1-29",
    },
    {
      id: 58,
      name: "Al-Mujadila",
      verses: "The Pleading Woman - 22 Verses",
      chapters: "1-22",
    },
    {
      id: 59,
      name: "Al-Hashr",
      verses: "The Exile - 24 Verses",
      chapters: "1-24",
    },
    {
      id: 60,
      name: "Al-Mumtahanah",
      verses: "The Examined One - 13 Verses",
      chapters: "1-13",
    },
    {
      id: 61,
      name: "As-Saff",
      verses: "The Ranks - 14 Verses",
      chapters: "1-14",
    },
    {
      id: 62,
      name: "Al-Jumu'ah",
      verses: "The Congregation - 11 Verses",
      chapters: "1-11",
    },
    {
      id: 63,
      name: "Al-Munafiqun",
      verses: "The Hypocrites - 11 Verses",
      chapters: "1-11",
    },
    {
      id: 64,
      name: "At-Taghabun",
      verses: "The Mutual Disillusion - 18 Verses",
      chapters: "1-18",
    },
    {
      id: 65,
      name: "At-Talaq",
      verses: "The Divorce - 12 Verses",
      chapters: "1-12",
    },
    {
      id: 66,
      name: "At-Tahrim",
      verses: "The Prohibition - 12 Verses",
      chapters: "1-12",
    },
    {
      id: 67,
      name: "Al-Mulk",
      verses: "The Sovereignty - 30 Verses",
      chapters: "1-30",
    },
    {
      id: 68,
      name: "Al-Qalam",
      verses: "The Pen - 52 Verses",
      chapters: "1-52",
    },
    {
      id: 69,
      name: "Al-Haqqah",
      verses: "The Reality - 52 Verses",
      chapters: "1-52",
    },
    {
      id: 70,
      name: "Al-Ma'arij",
      verses: "The Ascending Stairways - 44 Verses",
      chapters: "1-44",
    },
    {
      id: 71,
      name: "Nuh",
      verses: "Noah - 28 Verses",
      chapters: "1-28",
    },
    {
      id: 72,
      name: "Al-Jinn",
      verses: "The Jinn - 28 Verses",
      chapters: "1-28",
    },
    {
      id: 73,
      name: "Al-Muzzammil",
      verses: "The Enshrouded One - 20 Verses",
      chapters: "1-20",
    },
    {
      id: 74,
      name: "Al-Muddathir",
      verses: "The Cloaked One - 56 Verses",
      chapters: "1-56",
    },
    {
      id: 75,
      name: "Al-Qiyamah",
      verses: "The Resurrection - 40 Verses",
      chapters: "1-40",
    },
    {
      id: 76,
      name: "Al-Insan",
      verses: "Man - 31 Verses",
      chapters: "1-31",
    },
    {
      id: 77,
      name: "Al-Mursalat",
      verses: "The Emissaries - 50 Verses",
      chapters: "1-50",
    },
    {
      id: 78,
      name: "An-Naba'",
      verses: "The Announcement - 40 Verses",
      chapters: "1-40",
    },
    {
      id: 79,
      name: "An-Nazi'at",
      verses: "Those who drag forth - 46 Verses",
      chapters: "1-46",
    },
    {
      id: 80,
      name: "'Abasa",
      verses: "He frowned - 42 Verses",
      chapters: "1-42",
    },
    {
      id: 81,
      name: "At-Takwir",
      verses: "The Overthrowing - 29 Verses",
      chapters: "1-29",
    },
    {
      id: 82,
      name: "Al-Infitar",
      verses: "The Cleaving - 19 Verses",
      chapters: "1-19",
    },
    {
      id: 83,
      name: "Al-Mutaffifin",
      verses: "Defrauding - 36 Verses",
      chapters: "1-36",
    },
    {
      id: 84,
      name: "Al-Inshiqaq",
      verses: "The Splitting Open - 25 Verses",
      chapters: "1-25",
    },
    {
      id: 85,
      name: "Al-Buruj",
      verses: "The Mansions of the Stars - 22 Verses",
      chapters: "1-22",
    },
    {
      id: 86,
      name: "At-Tariq",
      verses: "The Morning Star - 17 Verses",
      chapters: "1-17",
    },
    {
      id: 87,
      name: "Al-A'la",
      verses: "The Most High - 19 Verses",
      chapters: "1-19",
    },
    {
      id: 88,
      name: "Al-Ghashiyah",
      verses: "The Overwhelming - 26 Verses",
      chapters: "1-26",
    },
    {
      id: 89,
      name: "Al-Fajr",
      verses: "The Dawn - 30 Verses",
      chapters: "1-30",
    },
    {
      id: 90,
      name: "Al-Balad",
      verses: "The City - 20 Verses",
      chapters: "1-20",
    },
    {
      id: 91,
      name: "Ash-Shams",
      verses: "The Sun - 15 Verses",
      chapters: "1-15",
    },
    {
      id: 92,
      name: "Al-Layl",
      verses: "The Night - 21 Verses",
      chapters: "1-21",
    },
    {
      id: 93,
      name: "Ad-Duha",
      verses: "The Morning Hours - 11 Verses",
      chapters: "1-11",
    },
    {
      id: 94,
      name: "Ash-Sharh",
      verses: "The Relief - 8 Verses",
      chapters: "1-8",
    },
    {
      id: 95,
      name: "At-Tin",
      verses: "The Fig - 8 Verses",
      chapters: "1-8",
    },
    {
      id: 96,
      name: "Al-'Alaq",
      verses: "The Clot - 19 Verses",
      chapters: "1-19",
    },
    {
      id: 97,
      name: "Al-Qadr",
      verses: "The Power - 5 Verses",
      chapters: "1-5",
    },
    {
      id: 98,
      name: "Al-Bayyinah",
      verses: "The Clear Proof - 8 Verses",
      chapters: "1-8",
    },
    {
      id: 99,
      name: "Az-Zalzalah",
      verses: "The Earthquake - 8 Verses",
      chapters: "1-8",
    },
    {
      id: 100,
      name: "Al-'Adiyat",
      verses: "The Chargers - 11 Verses",
      chapters: "1-11",
    },
    {
      id: 101,
      name: "Al-Qari'ah",
      verses: "The Calamity - 11 Verses",
      chapters: "1-11",
    },
    {
      id: 102,
      name: "At-Takathur",
      verses: "The Rivalry in world increase - 8 Verses",
      chapters: "1-8",
    },
    {
      id: 103,
      name: "Al-'Asr",
      verses: "The Declining Day - 3 Verses",
      chapters: "1-3",
    },
    {
      id: 104,
      name: "Al-Humazah",
      verses: "The Traducer - 9 Verses",
      chapters: "1-9",
    },
    {
      id: 105,
      name: "Al-Fil",
      verses: "The Elephant - 5 Verses",
      chapters: "1-5",
    },
    {
      id: 106,
      name: "Quraish",
      verses: "Quraish - 4 Verses",
      chapters: "1-4",
    },
    {
      id: 107,
      name: "Al-Ma'un",
      verses: "The Small Kindnesses - 7 Verses",
      chapters: "1-7",
    },
    {
      id: 108,
      name: "Al-Kawthar",
      verses: "The Abundance - 3 Verses",
      chapters: "1-3",
    },
    {
      id: 109,
      name: "Al-Kafirun",
      verses: "The Disbelievers - 6 Verses",
      chapters: "1-6",
    },
    {
      id: 110,
      name: "An-Nasr",
      verses: "The Divine Support - 3 Verses",
      chapters: "1-3",
    },
    {
      id: 111,
      name: "Al-Masad",
      verses: "The Palm Fiber - 5 Verses",
      chapters: "1-5",
    },
    {
      id: 112,
      name: "Al-Ikhlas",
      verses: "The Sincerity - 4 Verses",
      chapters: "1-4",
    },
    {
      id: 113,
      name: "Al-Falaq",
      verses: "The Daybreak - 5 Verses",
      chapters: "1-5",
    },
    {
      id: 114,
      name: "An-Nas",
      verses: "The Mankind - 6 Verses",
      chapters: "1-6",
    }
  ];
  